/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cp2.test;

import java.awt.Cursor;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ssianrosalejos
 */
public class editEmployee extends javax.swing.JFrame {
    String userID;
    private static final String FILE_PATH = System.getProperty("user.dir") + "/src/cp2/test/MotorPH Employee Data.csv";
    private static final int HEADER_ROWS = 1;
    /**
     * Creates new form editEmployee
     */
    public void updateUserNameLabel(String userName) {
        if (userNameLabel != null) {
            userNameLabel.setText("Welcome, " + userName + "!");
            userID = userName;
        }
    }
    public editEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        mainMenu = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        deleteEmployeeButton = new javax.swing.JLabel();
        addEmployeeButton = new javax.swing.JLabel();
        viewPayrollButton = new javax.swing.JLabel();
        searchEmployeeButton = new javax.swing.JLabel();
        saveButton = new javax.swing.JLabel();
        discardButton = new javax.swing.JLabel();
        empDetails = new javax.swing.JPanel();
        phoneLabel = new javax.swing.JLabel();
        birthdayLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        supervisorLabel = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        position = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        birthday1 = new javax.swing.JTextField();
        phone1 = new javax.swing.JTextField();
        status1 = new javax.swing.JTextField();
        supervisor1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        empID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(950, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        userNameLabel.setText("userName");
        jPanel1.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        mainMenu.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        mainMenu.setForeground(new java.awt.Color(0, 153, 204));
        mainMenu.setText("Main Menu");
        mainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainMenuMouseEntered(evt);
            }
        });
        jPanel1.add(mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        logout.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(102, 102, 102));
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        deleteEmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/deleteEmployeeButton_unselected.png"))); // NOI18N
        deleteEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteEmployeeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteEmployeeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteEmployeeButtonMouseExited(evt);
            }
        });
        jPanel1.add(deleteEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, -1, -1));

        addEmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/addEmployeeButton_unselected.png"))); // NOI18N
        addEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMouseExited(evt);
            }
        });
        jPanel1.add(addEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, -1, -1));

        viewPayrollButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/viewPayrollButton_unselected.png"))); // NOI18N
        viewPayrollButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPayrollButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewPayrollButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewPayrollButtonMouseExited(evt);
            }
        });
        jPanel1.add(viewPayrollButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, -1, -1));

        searchEmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/searchEmployeeButton_unselected.png"))); // NOI18N
        searchEmployeeButton.setAlignmentY(0.0F);
        searchEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchEmployeeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchEmployeeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchEmployeeButtonMouseExited(evt);
            }
        });
        jPanel1.add(searchEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, -1));

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/saveButton_unselected.png"))); // NOI18N
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveButtonMouseExited(evt);
            }
        });
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        discardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/discardButton_unselected.png"))); // NOI18N
        discardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                discardButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                discardButtonMouseExited(evt);
            }
        });
        jPanel1.add(discardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        empDetails.setBackground(new java.awt.Color(241, 241, 241));
        empDetails.setOpaque(false);

        phoneLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        phoneLabel.setText("Phone Number");

        birthdayLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        birthdayLabel.setText("Birthday");

        statusLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        statusLabel.setText("Status");

        supervisorLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        supervisorLabel.setText("Supervisor");

        positionLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        positionLabel.setText("Position");

        nameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        nameLabel.setText("Name");

        position.setText("position");
        position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionActionPerformed(evt);
            }
        });

        name1.setText("name");
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });

        birthday1.setText("birthday");
        birthday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthday1ActionPerformed(evt);
            }
        });

        phone1.setText("phone");
        phone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone1ActionPerformed(evt);
            }
        });

        status1.setText("status");
        status1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status1ActionPerformed(evt);
            }
        });

        supervisor1.setText("supervisor");
        supervisor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout empDetailsLayout = new javax.swing.GroupLayout(empDetails);
        empDetails.setLayout(empDetailsLayout);
        empDetailsLayout.setHorizontalGroup(
            empDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empDetailsLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(nameLabel)
                .addGap(17, 17, 17)
                .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(empDetailsLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(birthdayLabel)
                .addGap(18, 18, 18)
                .addComponent(birthday1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(empDetailsLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(phoneLabel)
                .addGap(18, 18, 18)
                .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(empDetailsLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(statusLabel)
                .addGap(17, 17, 17)
                .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(empDetailsLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(supervisorLabel)
                .addGap(18, 18, 18)
                .addComponent(supervisor1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(empDetailsLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(positionLabel)
                .addGap(18, 18, 18)
                .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        empDetailsLayout.setVerticalGroup(
            empDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empDetailsLayout.createSequentialGroup()
                .addGroup(empDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empDetailsLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(nameLabel))
                    .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(empDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthday1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdayLabel))
                .addGap(7, 7, 7)
                .addGroup(empDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel))
                .addGap(7, 7, 7)
                .addGroup(empDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusLabel)
                    .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(empDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supervisorLabel)
                    .addComponent(supervisor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(empDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(positionLabel)))
        );

        jPanel1.add(empDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 340, 190));

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 200));

        searchButton.setText("Search");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("Search employee number:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 196, Short.MAX_VALUE)
                    .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(searchButton)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchButton))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 440, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/backgroundImage.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 500));

        setSize(new java.awt.Dimension(950, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuMouseEntered
        mainMenu.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_mainMenuMouseEntered

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        System.exit(0);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutMouseEntered

    private void deleteEmployeeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEmployeeButtonMouseEntered
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/deleteEmployeeButton_selected.png");
        deleteEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_deleteEmployeeButtonMouseEntered

    private void deleteEmployeeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEmployeeButtonMouseExited
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/deleteEmployeeButton_unselected.png");
        deleteEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_deleteEmployeeButtonMouseExited

    private void addEmployeeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeButtonMouseEntered
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/addEmployeeButton_selected.png");
        addEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_addEmployeeButtonMouseEntered

    private void addEmployeeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeButtonMouseExited
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/addEmployeeButton_unselected.png");
        addEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_addEmployeeButtonMouseExited

    private void viewPayrollButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPayrollButtonMouseEntered
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/viewPayrollButton_selected.png");
        viewPayrollButton.setIcon(selectedIcon);
    }//GEN-LAST:event_viewPayrollButtonMouseEntered

    private void viewPayrollButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPayrollButtonMouseExited
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/viewPayrollButton_unselected.png");
        viewPayrollButton.setIcon(selectedIcon);
    }//GEN-LAST:event_viewPayrollButtonMouseExited

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        int EmpID;
        String empIDText = empID.getText();

        try {EmpID = Integer.parseInt(empIDText);
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Invalid EmpID format. Please enter a valid Employee Number.", "Invalid EmpID", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try (BufferedReader reader = new BufferedReader(new FileReader(FILE_PATH))) {
            for (int i = 0; i < HEADER_ROWS; i++) {
                reader.readLine();
            }
            String line;
            boolean found = false;
            while ((line = reader.readLine()) != null) {
                String[] employeeData = line.split(",");
                if (Integer.parseInt(employeeData[0]) == EmpID) {
                    found = true;
                    position.setText(employeeData[1] + ", " + employeeData[2]);
                    position.setText(employeeData[11]);
                    position.setText(employeeData[12]);
                    position.setText(employeeData[10]);
                    position.setText(employeeData[3]);
                    position.setText(employeeData[5]);
                    empDetails.setVisible(true);
                }
            }
            if (!found) { // Print message only if employee is not found
                searchEmployee searchResult = new searchEmployee();
                JOptionPane.showMessageDialog(searchResult, "Employee not found. Please enter a valid Employee Number.", "Invalid EmpID", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException e) {
            System.out.println("File not found.");
        } finally {

        }

    }//GEN-LAST:event_searchButtonMouseClicked

    private void searchEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchEmployeeButtonMouseClicked
        // TODO add your handling code here:
        searchEmployee search = new searchEmployee();
        search.updateUserNameLabel(userID);
        search.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_searchEmployeeButtonMouseClicked

    private void searchEmployeeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchEmployeeButtonMouseEntered
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/searchEmployeeButton_selected.png");
        searchEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_searchEmployeeButtonMouseEntered

    private void searchEmployeeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchEmployeeButtonMouseExited
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/searchEmployeeButton_unselected.png");
        searchEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_searchEmployeeButtonMouseExited

    private void positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void birthday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthday1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthday1ActionPerformed

    private void phone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone1ActionPerformed

    private void status1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status1ActionPerformed

    private void supervisor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervisor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supervisor1ActionPerformed

    private void mainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuMouseClicked
        Menu menu = new Menu();
        menu.applyUserName(userID);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainMenuMouseClicked

    private void deleteEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEmployeeButtonMouseClicked
        // TODO add your handling code here:
        searchEmployee search = new searchEmployee();
        search.updateUserNameLabel(userID);
        search.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_deleteEmployeeButtonMouseClicked

    private void addEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeButtonMouseClicked
        // TODO add your handling code here:
        addEmployee add = new addEmployee();
        add.updateUserNameLabel(userID);
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addEmployeeButtonMouseClicked

    private void viewPayrollButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPayrollButtonMouseClicked
        // TODO add your handling code here:
        viewPayroll view = new viewPayroll();
        view.updateUserNameLabel(userID);
        view.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewPayrollButtonMouseClicked

    private void saveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseEntered
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/saveButton_selected.png");
        saveButton.setIcon(selectedIcon);
    }//GEN-LAST:event_saveButtonMouseEntered

    private void discardButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discardButtonMouseEntered
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/discardButton_selected.png");
        discardButton.setIcon(selectedIcon);
    }//GEN-LAST:event_discardButtonMouseEntered

    private void saveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseExited
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/saveButton_unselected.png");
        saveButton.setIcon(selectedIcon);
    }//GEN-LAST:event_saveButtonMouseExited

    private void discardButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discardButtonMouseExited
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/discardButton_unselected.png");
        discardButton.setIcon(selectedIcon);
    }//GEN-LAST:event_discardButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addEmployeeButton;
    private javax.swing.JTextField birthday1;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JLabel deleteEmployeeButton;
    private javax.swing.JLabel discardButton;
    private javax.swing.JPanel empDetails;
    private javax.swing.JTextField empID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel mainMenu;
    private javax.swing.JTextField name1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField phone1;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField position;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JLabel saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchEmployeeButton;
    private javax.swing.JTextField status1;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField supervisor1;
    private javax.swing.JLabel supervisorLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel viewPayrollButton;
    // End of variables declaration//GEN-END:variables
}
