/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cp2.test;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ssianrosalejos
 */
public class searchEmployee extends javax.swing.JFrame {
    String userID;
    private static final String FILE_PATH = System.getProperty("user.dir") + "/src/cp2/test/MotorPH Employee Data.csv";
    private static final int HEADER_ROWS = 1;
    /**
     * Creates new form searchEmployee
     */
    public void updateUserNameLabel(String userName) {
        if (userNameLabel != null) {
            userNameLabel.setText("Welcome, " + userName + "!");
            userID = userName;
        }
    }
    
    public searchEmployee() {
        initComponents();
        empDetails.setVisible(false);
        empID.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                // Not used in this implementation
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    searchButtonMouseClicked(null); // Call loginButtonMouseClicked method when Enter key is pressed
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
                // Not used in this implementation
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        mainMenu = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        editEmployeeButton = new javax.swing.JLabel();
        deleteEmployeeButton = new javax.swing.JLabel();
        addEmployeeButton = new javax.swing.JLabel();
        viewPayrollButton = new javax.swing.JLabel();
        empDetails = new javax.swing.JPanel();
        phone = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        birthdayLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        supervisor = new javax.swing.JLabel();
        supervisorLabel = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        empID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Portal - Search Employee");
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(950, 500));
        setSize(new java.awt.Dimension(950, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        userNameLabel.setText("userName");
        jPanel1.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        mainMenu.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        mainMenu.setForeground(new java.awt.Color(0, 153, 204));
        mainMenu.setText("Main Menu");
        mainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainMenuMouseEntered(evt);
            }
        });
        jPanel1.add(mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        logout.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(102, 102, 102));
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        editEmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/editEmployeeButton_unselected.png"))); // NOI18N
        editEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editEmployeeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editEmployeeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editEmployeeButtonMouseExited(evt);
            }
        });
        jPanel1.add(editEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, -1));

        deleteEmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/deleteEmployeeButton_unselected.png"))); // NOI18N
        deleteEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteEmployeeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteEmployeeButtonMouseExited(evt);
            }
        });
        jPanel1.add(deleteEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, -1, -1));

        addEmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/addEmployeeButton_unselected.png"))); // NOI18N
        addEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMouseExited(evt);
            }
        });
        jPanel1.add(addEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, -1, -1));

        viewPayrollButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/viewPayrollButton_unselected.png"))); // NOI18N
        viewPayrollButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPayrollButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewPayrollButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewPayrollButtonMouseExited(evt);
            }
        });
        jPanel1.add(viewPayrollButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, -1, -1));

        empDetails.setBackground(new java.awt.Color(241, 241, 241));
        empDetails.setOpaque(false);
        empDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phone.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        phone.setText("Phone Number");
        empDetails.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 53, -1, -1));

        birthday.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        birthday.setText("Birthday");
        empDetails.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 29, -1, -1));

        phoneLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        phoneLabel.setText("Phone Number");
        empDetails.add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 53, -1, -1));

        birthdayLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        birthdayLabel.setText("Birthday");
        empDetails.add(birthdayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 29, -1, -1));

        statusLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        statusLabel.setText("Status");
        empDetails.add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 77, -1, -1));

        status.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        status.setText("Status");
        empDetails.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 77, -1, -1));

        supervisor.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        supervisor.setText("Supervisor");
        empDetails.add(supervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 101, -1, -1));

        supervisorLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        supervisorLabel.setText("Supervisor");
        empDetails.add(supervisorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 101, -1, -1));

        positionLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        positionLabel.setText("Position");
        empDetails.add(positionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 125, -1, -1));

        position.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        position.setText("Position");
        empDetails.add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 125, -1, -1));

        name.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        name.setText("Name");
        empDetails.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 5, -1, -1));

        nameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        nameLabel.setText("Name");
        empDetails.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 5, -1, -1));

        jPanel1.add(empDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 340, 170));

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 200));

        searchButton.setText("Search");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("Search employee number:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 196, Short.MAX_VALUE)
                    .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(searchButton)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchButton))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 440, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/backgroundImage.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 500));

        setSize(new java.awt.Dimension(950, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        int EmpID;
        String empIDText = empID.getText();
        
        try {EmpID = Integer.parseInt(empIDText);
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Invalid EmpID format. Please enter a valid Employee Number.", "Invalid EmpID", JOptionPane.ERROR_MESSAGE);
        return;
        }
        try (BufferedReader reader = new BufferedReader(new FileReader(FILE_PATH))) {
            for (int i = 0; i < HEADER_ROWS; i++) {
                reader.readLine();
            }
            String line;
            boolean found = false; 
            while ((line = reader.readLine()) != null) {
                String[] employeeData = line.split(",");
                if (Integer.parseInt(employeeData[0]) == EmpID) {
                    found = true;
                    name.setText(employeeData[1] + ", " + employeeData[2]);
                    position.setText(employeeData[11]);
                    supervisor.setText(employeeData[12]);
                    status.setText(employeeData[10]);
                    birthday.setText(employeeData[3]);
                    phone.setText(employeeData[5]);
                    empDetails.setVisible(true);
               }
            }
             if (!found) { // Print message only if employee is not found
                 searchEmployee searchResult = new searchEmployee();
            JOptionPane.showMessageDialog(searchResult, "Employee not found. Please enter a valid Employee Number.", "Invalid EmpID", JOptionPane.ERROR_MESSAGE);
        }
        } catch (IOException e) {
            System.out.println("File not found.");
        } finally {
           
        }
        
        
    }//GEN-LAST:event_searchButtonMouseClicked

    public void searchResult (String n, String p, String sup, String stat, String bday, String phn){
        String nameResult = n;
        String positionResult = p;
        String supervisorResult = sup;
        String statusResult = stat;
        String birthdayResult = bday;
        String phoneResult = phn;
        

        name.setText(nameResult);
        System.out.println(nameResult);
        name.setVisible(true);
        nameLabel.setVisible(true);
        position.setVisible(true);
        positionLabel.setVisible(true);
        supervisor.setVisible(true);
        supervisorLabel.setVisible(true);
        status.setVisible(true);
        statusLabel.setVisible(true);
        birthday.setVisible(true);
        birthdayLabel.setVisible(true);
        phone.setVisible(true);
        phoneLabel.setVisible(true);

    }
    

    private void mainMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuMouseEntered
        mainMenu.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_mainMenuMouseEntered

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        System.exit(0);
    }//GEN-LAST:event_logoutMouseClicked

    private void editEmployeeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEmployeeButtonMouseEntered
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/editEmployeeButton_selected.png");
        editEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_editEmployeeButtonMouseEntered

    private void editEmployeeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEmployeeButtonMouseExited
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/editEmployeeButton_unselected.png");
        editEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_editEmployeeButtonMouseExited

    private void deleteEmployeeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEmployeeButtonMouseEntered
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/deleteEmployeeButton_selected.png");
        deleteEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_deleteEmployeeButtonMouseEntered

    private void deleteEmployeeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEmployeeButtonMouseExited
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/deleteEmployeeButton_unselected.png");
        deleteEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_deleteEmployeeButtonMouseExited

    private void addEmployeeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeButtonMouseEntered
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/addEmployeeButton_selected.png");
        addEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_addEmployeeButtonMouseEntered

    private void addEmployeeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeButtonMouseExited
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/addEmployeeButton_unselected.png");
        addEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_addEmployeeButtonMouseExited

    private void viewPayrollButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPayrollButtonMouseEntered
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/viewPayrollButton_selected.png");
        viewPayrollButton.setIcon(selectedIcon);
    }//GEN-LAST:event_viewPayrollButtonMouseEntered

    private void viewPayrollButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPayrollButtonMouseExited
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/viewPayrollButton_unselected.png");
        viewPayrollButton.setIcon(selectedIcon);
    }//GEN-LAST:event_viewPayrollButtonMouseExited

    private void mainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuMouseClicked
        Menu menu = new Menu();
        menu.applyUserName(userID);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainMenuMouseClicked

    private void addEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeButtonMouseClicked
        // TODO add your handling code here:
        addEmployee add = new addEmployee();
        add.updateUserNameLabel(userID);
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addEmployeeButtonMouseClicked

    private void viewPayrollButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPayrollButtonMouseClicked
        // TODO add your handling code here:
        viewPayroll view = new viewPayroll();
        view.updateUserNameLabel(userID);
        view.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewPayrollButtonMouseClicked

    private void editEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEmployeeButtonMouseClicked
        // TODO add your handling code here:
        editEmployee edit = new editEmployee();
        edit.updateUserNameLabel(userID);
        edit.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editEmployeeButtonMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addEmployeeButton;
    private javax.swing.JLabel birthday;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JLabel deleteEmployeeButton;
    private javax.swing.JLabel editEmployeeButton;
    private javax.swing.JPanel empDetails;
    private javax.swing.JTextField empID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel mainMenu;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel position;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel status;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel supervisor;
    private javax.swing.JLabel supervisorLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel viewPayrollButton;
    // End of variables declaration//GEN-END:variables
}
