/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cp2.test;

import java.awt.Cursor;
import javax.swing.ImageIcon;

/**
 *
 * @author ssianrosalejos
 */
public class viewPayroll extends javax.swing.JFrame {
    String userID;

    /**
     * Creates new form viewPayroll
     */
    public void updateUserNameLabel(String userName) {
        if (userNameLabel != null) {
            userNameLabel.setText("Welcome, " + userName + "!");
            userID = userName;
        }
    }
    public viewPayroll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        empID = new javax.swing.JLabel();
        mainMenu = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        downloadButton = new javax.swing.JLabel();
        printButton = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        payslip = new javax.swing.JTextArea();
        dateField = new javax.swing.JTextField();
        viewSalaryButton = new javax.swing.JButton();
        deleteEmployeeButton = new javax.swing.JLabel();
        searchEmployeeButton = new javax.swing.JLabel();
        addEmployeeButton = new javax.swing.JLabel();
        editEmployeeButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        userNameLabel.setText("userName");
        jPanel1.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        empID.setText("empID");
        jPanel1.add(empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, 30));

        mainMenu.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        mainMenu.setForeground(new java.awt.Color(0, 153, 204));
        mainMenu.setText("Main Menu");
        mainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainMenuMouseEntered(evt);
            }
        });
        jPanel1.add(mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        logout.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(102, 102, 102));
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        dateLabel.setText("Please enter the date you want to include:");
        jPanel1.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        downloadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/downloadButton_unselected.png"))); // NOI18N
        jPanel1.add(downloadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, -1));

        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/printButton_unselected.png"))); // NOI18N
        jPanel1.add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));

        payslip.setColumns(20);
        payslip.setRows(5);
        payslip.setText("SAMPLE ONLY\nBasic Salary(Base Computation only): 90,000.00\n\nRice Subsidy: 1,500.00\nPhone Allowance: 2,000.00\nClothing Allowance: 1,000.00\n\nTotal Monthly Hours:            176Hrs. 0mins. \nHourly Rate:                    535.71\n                               -------------\nTotal Gross Monthly salary:     94,284.96\n\nLess:\nSSS:                1,125.00\nPhilHealth:         900.00\nPagIbig:            100.00     (2,125.00)\n                              -----------\nTaxable Income:                92,159.96\n\nLess:\nWithholding Tax:               (18,480.89)\n                              -----------\nNet Salary:                    73,679.07\n                              ===========");
        jScrollPane1.setViewportView(payslip);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 590, 340));

        dateField.setText("dd/mm/yyyy");
        jPanel1.add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 170, -1));

        viewSalaryButton.setText("View Monthly Salary");
        jPanel1.add(viewSalaryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        deleteEmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/deleteEmployeeButton_unselected.png"))); // NOI18N
        deleteEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteEmployeeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteEmployeeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteEmployeeButtonMouseExited(evt);
            }
        });
        jPanel1.add(deleteEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, -1, -1));

        searchEmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/searchEmployeeButton_unselected.png"))); // NOI18N
        searchEmployeeButton.setAlignmentY(0.0F);
        searchEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchEmployeeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchEmployeeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchEmployeeButtonMouseExited(evt);
            }
        });
        jPanel1.add(searchEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, -1));

        addEmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/addEmployeeButton_unselected.png"))); // NOI18N
        addEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMouseExited(evt);
            }
        });
        jPanel1.add(addEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, -1, -1));

        editEmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/editEmployeeButton_unselected.png"))); // NOI18N
        editEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editEmployeeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editEmployeeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editEmployeeButtonMouseExited(evt);
            }
        });
        jPanel1.add(editEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cp2/test/backgroundImage.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 500));

        setSize(new java.awt.Dimension(950, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuMouseEntered
        mainMenu.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_mainMenuMouseEntered

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        System.exit(0);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutMouseEntered

    private void deleteEmployeeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEmployeeButtonMouseEntered
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/deleteEmployeeButton_selected.png");
        deleteEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_deleteEmployeeButtonMouseEntered

    private void deleteEmployeeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEmployeeButtonMouseExited
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/deleteEmployeeButton_unselected.png");
        deleteEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_deleteEmployeeButtonMouseExited

    private void searchEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchEmployeeButtonMouseClicked
        // TODO add your handling code here:
        searchEmployee search = new searchEmployee();
        search.updateUserNameLabel(userID);
        search.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_searchEmployeeButtonMouseClicked

    private void searchEmployeeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchEmployeeButtonMouseEntered
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/searchEmployeeButton_selected.png");
        searchEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_searchEmployeeButtonMouseEntered

    private void searchEmployeeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchEmployeeButtonMouseExited
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/searchEmployeeButton_unselected.png");
        searchEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_searchEmployeeButtonMouseExited

    private void editEmployeeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEmployeeButtonMouseEntered
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/editEmployeeButton_selected.png");
        editEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_editEmployeeButtonMouseEntered

    private void editEmployeeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEmployeeButtonMouseExited
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/editEmployeeButton_unselected.png");
        editEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_editEmployeeButtonMouseExited

    private void mainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuMouseClicked
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.applyUserName(userID);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainMenuMouseClicked

    private void deleteEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEmployeeButtonMouseClicked
        // TODO add your handling code here:
        searchEmployee search = new searchEmployee();
        search.updateUserNameLabel(userID);
        search.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_deleteEmployeeButtonMouseClicked

    private void editEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEmployeeButtonMouseClicked
        // TODO add your handling code here:
        editEmployee edit = new editEmployee();
        edit.updateUserNameLabel(userID);
        edit.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editEmployeeButtonMouseClicked

    private void addEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeButtonMouseClicked
        // TODO add your handling code here:
        addEmployee add = new addEmployee();
        add.updateUserNameLabel(userID);
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addEmployeeButtonMouseClicked

    private void addEmployeeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeButtonMouseEntered
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/addEmployeeButton_selected.png");
        addEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_addEmployeeButtonMouseEntered

    private void addEmployeeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeButtonMouseExited
        // TODO add your handling code here:
        ImageIcon selectedIcon = new ImageIcon(System.getProperty("user.dir") + "/src/cp2/test/addEmployeeButton_unselected.png");
        addEmployeeButton.setIcon(selectedIcon);
    }//GEN-LAST:event_addEmployeeButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewPayroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addEmployeeButton;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel deleteEmployeeButton;
    private javax.swing.JLabel downloadButton;
    private javax.swing.JLabel editEmployeeButton;
    private javax.swing.JLabel empID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel mainMenu;
    private javax.swing.JTextArea payslip;
    private javax.swing.JLabel printButton;
    private javax.swing.JLabel searchEmployeeButton;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JButton viewSalaryButton;
    // End of variables declaration//GEN-END:variables
}
